
#Config for the spawn blocking torches
[spawn_blockers]
	#Range of the alone torch.
	#Range: > 0
	alone_torch_range = 64
	#Range of the bat torch.
	#Range: > 0
	bat_torch_range = 64

	#Config for hostile mob spawn blocking torches
	[spawn_blockers.hostile]
		#Range of the small torch.
		#Range: > 0
		small_torch_range = 16
		#Range of the medium torch.
		#Range: > 0
		medium_torch_range = 32
		#Range of the grand torch.
		#Range: > 0
		grand_torch_range = 64
		#Range of the mega torch.
		#Range: > 0
		mega_torch_range = 128
		#Entities blocked by hostile mob spawn blocking torches
		blocked_entities = ["minecraft:blaze", "minecraft:cave_spider", "minecraft:creeper", "minecraft:drowned", "minecraft:elder_guardian", "minecraft:ender_dragon", "minecraft:enderman", "minecraft:endermite", "minecraft:evoker", "minecraft:ghast", "minecraft:giant", "minecraft:guardian", "minecraft:hoglin", "minecraft:husk", "minecraft:illusioner", "minecraft:magma_cube", "minecraft:phantom", "minecraft:piglin", "minecraft:piglin_brute", "minecraft:pillager", "minecraft:ravager", "minecraft:shulker", "minecraft:silverfish", "minecraft:skeleton", "minecraft:slime", "minecraft:spider", "minecraft:stray", "minecraft:vex", "minecraft:vindicator", "minecraft:witch", "minecraft:wither", "minecraft:wither_skeleton", "minecraft:zoglin", "minecraft:zombie", "minecraft:zombie_villager", "minecraft:zombified_piglin"]

#Config for the sound muffling torches
[sound_mufflers]
	#Range of the sound muffling torch.
	#Range: > 0
	sound_muffling_torch_range = 64
	#Sound categories that shall be muffled by the sound muffling torch
	#Available Sound Categories: MASTER, MUSIC, RECORDS, WEATHER, BLOCKS, HOSTILE, NEUTRAL, PLAYERS, AMBIENT, VOICE
	sound_muffling_torch_to_muffle_sounds = ["HOSTILE", "NEUTRAL", "BLOCKS", "RECORDS"]

#Config for the chicken egg torch
[chicken_egg_torch]
	#Range of the chicken egg torch.
	#Range: > 0
	range = 16
	#If 'false' chicken egg spawning is allowed and is blocked by chicken egg torches.
	#If 'true' chicken egg spawning is disabled and is enabled by chicken egg torches.
	should_invert_chicken_egg_blocking = false

